### ISSUE TITLE
Provide Helm chart for configuring Azure Pipelines Environment

### ISSUE THREAD

**Issue by tomkerkhove** [CoditEU/charts#1]
Provide Helm chart for configuring Azure Pipelines Environment by using the generic account option.

**Comment by tomkerkhove** [comment]
@krottiers An alpha version is ready, would you mind reviewing it please?

**Comment by krottiers** [comment]
@tomkerkhove looks good. For the moment this is only a deployment with clusterwide access right? Maybe nice to have an option to be able to limit to specific namespace. Would work nice if clusters are shared across teams and your own team only has access to it's own namespace.

**Comment by tomkerkhove** [comment]
That's a good suggestion. Do you think this should be in v0.1 or as a follow-up feature?

I think a follow-up one should be ok, maybe?

**Comment by krottiers** [comment]
Follow feature is perfect. No need to put it in first version.

**Comment by tomkerkhove** [comment]
In theory it's already scoped to a namespace given it's only going to create a rolebinding in the namespace it's being deployed in: https://github.com/CoditEU/charts/blob/master/azure-pipeline-environment/templates/rolebinding.yaml

**Comment by krottiers** [comment]
The service account hasn't got a namespace assigned so will be deployed in the namespace where the helm chart is installed. Will the helm chart always be fully installed in the namespace that needs to be accessed by Azure DevOps?

**Comment by tomkerkhove** [comment]
Yes that is correct, except for the cluster role which is on cluster level.
